// <auto-generated>
//     Generated by tools/sync-diagnostic-codes.ps1 from spec/diagnostics.registry.json.
//     Do not edit. Change the registry, or the specification behind it, and regenerate.
// </auto-generated>

#nullable enable

using System.Collections.Immutable;

namespace Namespace2Xml.Diagnostics;

public static partial class DiagnosticCodes
{
    /// <summary>
    /// Every code in the Section 22 registry, in registry order, with the four facts the
    /// registry declares itself authoritative for.
    /// </summary>
    public static ImmutableArray<DiagnosticCodeInfo> All { get; } =
    [
        new DiagnosticCodeInfo("CLI001", DiagnosticSeverity.Error,
            "once per invocation",
            "Invalid command line or option value",
            []),
        new DiagnosticCodeInfo("PARSE001", DiagnosticSeverity.Error,
            "once per failing source",
            "Malformed namespace, JSON, YAML, XML, or scheme syntax",
            ["source", "line", "column"]),
        new DiagnosticCodeInfo("PARSE002", DiagnosticSeverity.Error,
            "once per failing source",
            "Invalid or unsupported character encoding",
            ["source", "line", "column"]),
        new DiagnosticCodeInfo("SCHEME001", DiagnosticSeverity.Error,
            "once per declaration",
            "Unknown directive, value, or illegal option/type combination",
            ["source", "line", "column", "path", "declaration"]),
        new DiagnosticCodeInfo("SCHEME002", DiagnosticSeverity.Error,
            "once per expanded declaration",
            "Ambiguous canonical/simple scheme path",
            ["source", "line", "column", "path", "declaration"]),
        new DiagnosticCodeInfo("WILDCARD001", DiagnosticSeverity.Error,
            "once per rule",
            "Invalid, undefined, or mixed capture",
            ["source", "line", "column", "path"]),
        new DiagnosticCodeInfo("WILDCARD002", DiagnosticSeverity.Error,
            "once per invocation",
            "Nonterminating expansion or wildcard limit",
            ["rule"]),
        new DiagnosticCodeInfo("REFERENCE001", DiagnosticSeverity.Error,
            "once per reachable owning value",
            "Malformed or free-wildcard reference",
            ["source", "line", "column", "path"]),
        new DiagnosticCodeInfo("REFERENCE002", DiagnosticSeverity.Error,
            "once per reachable owning value",
            "Missing reference",
            ["source", "line", "column", "path"]),
        new DiagnosticCodeInfo("REFERENCE003", DiagnosticSeverity.Error,
            "once per canonically distinct reachable cycle",
            "Reference cycle",
            ["source", "line", "column", "path"]),
        new DiagnosticCodeInfo("REFERENCE004", DiagnosticSeverity.Error,
            "once per reachable owning value",
            "Ambiguous reference alias",
            ["source", "line", "column", "path"]),
        new DiagnosticCodeInfo("REFERENCE005", DiagnosticSeverity.Error,
            "once per reachable owning value",
            "Non-scalar reference target",
            ["source", "line", "column", "path"]),
        new DiagnosticCodeInfo("TYPE001", DiagnosticSeverity.Error,
            "once per path and applicable source/output instance",
            "Invalid shape, input merge conflict, root removal, or transformation target",
            ["source", "line", "column", "path", "declaration", "destination"]),
        new DiagnosticCodeInfo("TYPE002", DiagnosticSeverity.Warning,
            "once per path and output instance",
            "Shape conflict resolved by precedence",
            ["source", "path", "destination"]),
        new DiagnosticCodeInfo("FLAT001", DiagnosticSeverity.Error,
            "once per projected key and output instance",
            "Distinct logical paths collide after flat-format projection or normalization",
            ["path", "destination"]),
        new DiagnosticCodeInfo("SHELL001", DiagnosticSeverity.Error,
            "once per projected key and output instance",
            "Invalid quoted-namespace shell identifier",
            ["path", "destination"]),
        new DiagnosticCodeInfo("XML001", DiagnosticSeverity.Error,
            "once per failing document",
            "DTD, external entity/resource, or prohibited XML feature",
            ["source", "line", "column"]),
        new DiagnosticCodeInfo("XML002", DiagnosticSeverity.Error,
            "once per failing node or document",
            "Invalid XML name, namespace, declaration, or canonical address",
            ["source", "line", "column", "path"]),
        new DiagnosticCodeInfo("INI001", DiagnosticSeverity.Error,
            "once per path and output instance",
            "Value or name unsupported by `PortableIni1` options",
            ["path", "destination"]),
        new DiagnosticCodeInfo("COLLISION001", DiagnosticSeverity.Error,
            "once per rejected contribution after the first",
            "`filemerge=error` rejects a second contribution to one destination",
            ["declaration", "destination"]),
        new DiagnosticCodeInfo("SERIALIZE001", DiagnosticSeverity.Error,
            "once per output instance",
            "Output view cannot be serialized under the selected format/options",
            ["destination"]),
        new DiagnosticCodeInfo("PATH001", DiagnosticSeverity.Error,
            "once per destination",
            "Invalid, escaping, or insecure output path",
            ["declaration", "destination"]),
        new DiagnosticCodeInfo("PATH002", DiagnosticSeverity.Error,
            "once, for the failing destination",
            "Publication/open/write/flush failure",
            ["destination"]),
        new DiagnosticCodeInfo("LIMIT001", DiagnosticSeverity.Error,
            "once per invocation",
            "Non-wildcard resource limit exceeded",
            ["source", "line", "column", "path"]),
        new DiagnosticCodeInfo("WARN001", DiagnosticSeverity.Warning,
            "once per missing CLI path",
            "Missing input or scheme file",
            ["source"]),
        new DiagnosticCodeInfo("WARN002", DiagnosticSeverity.Warning,
            "once per alias category and scheme",
            "Deprecated alias",
            ["source", "line", "column", "declaration"]),
        new DiagnosticCodeInfo("WARN003", DiagnosticSeverity.Warning,
            "once per feature category and output file",
            "Unsupported metadata/comment discarded or normalized",
            ["source", "destination"]),
        new DiagnosticCodeInfo("WARN004", DiagnosticSeverity.Warning,
            "once per sequence path",
            "Native implicit sequences concatenate without explicit merge",
            ["source", "path"]),
        new DiagnosticCodeInfo("WARN005", DiagnosticSeverity.Warning,
            "once per folded contribution pair",
            "Output destination collision or cross-format override",
            ["destination"]),
        new DiagnosticCodeInfo("WARN006", DiagnosticSeverity.Warning,
            "once per input document",
            "Processing instruction discarded",
            ["source"]),
        new DiagnosticCodeInfo("WARN007", DiagnosticSeverity.Warning,
            "once per input document",
            "XML formatting whitespace discarded",
            ["source"]),
        new DiagnosticCodeInfo("WARN008", DiagnosticSeverity.Warning,
            "once per invocation",
            "Output plan contains no destinations",
            []),
        new DiagnosticCodeInfo("WARN009", DiagnosticSeverity.Warning,
            "once per declaration or expanded directive",
            "Scheme directive binds to no effective output/path or wildcard output creates no instance",
            ["source", "line", "column", "path", "declaration"]),
        new DiagnosticCodeInfo("WARN010", DiagnosticSeverity.Warning,
            "once per source contribution, canonical mapping path, and output instance",
            "Native JSON/YAML numeric mapping remains inferred as sequence in an output view",
            ["source", "path", "destination"]),
        new DiagnosticCodeInfo("WARN011", DiagnosticSeverity.Warning,
            "once per canonical path",
            "Later unmarked contribution aliases an existing XML component instead of overriding it",
            ["source", "path"]),
    ];

    /// <summary><c>CLI001</c> (error) — Invalid command line or option value.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <remarks>Cardinality: once per invocation.</remarks>
    public static DiagnosticOccurrence Cli001(
        DiagnosticPhase phase,
        string spec,
        string message) =>
        Create("CLI001", DiagnosticSeverity.Error, phase, spec, message,
            Invocation);

    /// <summary><c>PARSE001</c> (error) — Malformed namespace, JSON, YAML, XML, or scheme syntax.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the failing source this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <remarks>Cardinality: once per failing source.</remarks>
    public static DiagnosticOccurrence Parse001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null) =>
        Create("PARSE001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column);

    /// <summary><c>PARSE002</c> (error) — Invalid or unsupported character encoding.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the failing source this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <remarks>Cardinality: once per failing source.</remarks>
    public static DiagnosticOccurrence Parse002(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null) =>
        Create("PARSE002", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column);

    /// <summary><c>SCHEME001</c> (error) — Unknown directive, value, or illegal option/type combination.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the declaration this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <param name="declaration">Section 6.4.3 <c>declaration</c> member.</param>
    /// <remarks>Cardinality: once per declaration.</remarks>
    public static DiagnosticOccurrence Scheme001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null,
        string? declaration = null) =>
        Create("SCHEME001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, path: path, declaration: declaration);

    /// <summary><c>SCHEME002</c> (error) — Ambiguous canonical/simple scheme path.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the expanded declaration this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <param name="declaration">Section 6.4.3 <c>declaration</c> member.</param>
    /// <remarks>Cardinality: once per expanded declaration.</remarks>
    public static DiagnosticOccurrence Scheme002(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null,
        string? declaration = null) =>
        Create("SCHEME002", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, path: path, declaration: declaration);

    /// <summary><c>WILDCARD001</c> (error) — Invalid, undefined, or mixed capture.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the rule this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <remarks>Cardinality: once per rule.</remarks>
    public static DiagnosticOccurrence Wildcard001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null) =>
        Create("WILDCARD001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, path: path);

    /// <summary><c>WILDCARD002</c> (error) — Nonterminating expansion or wildcard limit.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="rule">Section 6.4.3 <c>rule</c> member.</param>
    /// <remarks>Cardinality: once per invocation.</remarks>
    public static DiagnosticOccurrence Wildcard002(
        DiagnosticPhase phase,
        string spec,
        string message,
        ImmutableArray<string> rule = default) =>
        Create("WILDCARD002", DiagnosticSeverity.Error, phase, spec, message,
            Invocation, rule: rule);

    /// <summary><c>REFERENCE001</c> (error) — Malformed or free-wildcard reference.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the reachable owning value this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <remarks>Cardinality: once per reachable owning value.</remarks>
    public static DiagnosticOccurrence Reference001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null) =>
        Create("REFERENCE001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, path: path);

    /// <summary><c>REFERENCE002</c> (error) — Missing reference.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the reachable owning value this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <remarks>Cardinality: once per reachable owning value.</remarks>
    public static DiagnosticOccurrence Reference002(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null) =>
        Create("REFERENCE002", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, path: path);

    /// <summary><c>REFERENCE003</c> (error) — Reference cycle.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the canonically distinct reachable cycle this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <remarks>Cardinality: once per canonically distinct reachable cycle.</remarks>
    public static DiagnosticOccurrence Reference003(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null) =>
        Create("REFERENCE003", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, path: path);

    /// <summary><c>REFERENCE004</c> (error) — Ambiguous reference alias.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the reachable owning value this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <remarks>Cardinality: once per reachable owning value.</remarks>
    public static DiagnosticOccurrence Reference004(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null) =>
        Create("REFERENCE004", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, path: path);

    /// <summary><c>REFERENCE005</c> (error) — Non-scalar reference target.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the reachable owning value this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <remarks>Cardinality: once per reachable owning value.</remarks>
    public static DiagnosticOccurrence Reference005(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null) =>
        Create("REFERENCE005", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, path: path);

    /// <summary><c>TYPE001</c> (error) — Invalid shape, input merge conflict, root removal, or transformation target.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the path and applicable source/output instance this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <param name="declaration">Section 6.4.3 <c>declaration</c> member.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once per path and applicable source/output instance.</remarks>
    public static DiagnosticOccurrence Type001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null,
        string? declaration = null,
        string? destination = null) =>
        Create("TYPE001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, path: path, declaration: declaration, destination: destination);

    /// <summary><c>TYPE002</c> (warning) — Shape conflict resolved by precedence.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the path and output instance this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once per path and output instance.</remarks>
    public static DiagnosticOccurrence Type002(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        string? path = null,
        string? destination = null) =>
        Create("TYPE002", DiagnosticSeverity.Warning, phase, spec, message,
            cardinalityKey, source: source, path: path, destination: destination);

    /// <summary><c>FLAT001</c> (error) — Distinct logical paths collide after flat-format projection or normalization.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the projected key and output instance this is emitted once per.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once per projected key and output instance.</remarks>
    public static DiagnosticOccurrence Flat001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? path = null,
        string? destination = null) =>
        Create("FLAT001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, path: path, destination: destination);

    /// <summary><c>SHELL001</c> (error) — Invalid quoted-namespace shell identifier.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the projected key and output instance this is emitted once per.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once per projected key and output instance.</remarks>
    public static DiagnosticOccurrence Shell001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? path = null,
        string? destination = null) =>
        Create("SHELL001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, path: path, destination: destination);

    /// <summary><c>XML001</c> (error) — DTD, external entity/resource, or prohibited XML feature.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the failing document this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <remarks>Cardinality: once per failing document.</remarks>
    public static DiagnosticOccurrence Xml001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null) =>
        Create("XML001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column);

    /// <summary><c>XML002</c> (error) — Invalid XML name, namespace, declaration, or canonical address.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the failing node or document this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <remarks>Cardinality: once per failing node or document.</remarks>
    public static DiagnosticOccurrence Xml002(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null) =>
        Create("XML002", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, path: path);

    /// <summary><c>INI001</c> (error) — Value or name unsupported by `PortableIni1` options.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the path and output instance this is emitted once per.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once per path and output instance.</remarks>
    public static DiagnosticOccurrence Ini001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? path = null,
        string? destination = null) =>
        Create("INI001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, path: path, destination: destination);

    /// <summary><c>COLLISION001</c> (error) — `filemerge=error` rejects a second contribution to one destination.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the rejected contribution after the first this is emitted once per.</param>
    /// <param name="declaration">Section 6.4.3 <c>declaration</c> member.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once per rejected contribution after the first.</remarks>
    public static DiagnosticOccurrence Collision001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? declaration = null,
        string? destination = null) =>
        Create("COLLISION001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, declaration: declaration, destination: destination);

    /// <summary><c>SERIALIZE001</c> (error) — Output view cannot be serialized under the selected format/options.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the output instance this is emitted once per.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once per output instance.</remarks>
    public static DiagnosticOccurrence Serialize001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? destination = null) =>
        Create("SERIALIZE001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, destination: destination);

    /// <summary><c>PATH001</c> (error) — Invalid, escaping, or insecure output path.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the destination this is emitted once per.</param>
    /// <param name="declaration">Section 6.4.3 <c>declaration</c> member.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once per destination.</remarks>
    public static DiagnosticOccurrence Path001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? declaration = null,
        string? destination = null) =>
        Create("PATH001", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, declaration: declaration, destination: destination);

    /// <summary><c>PATH002</c> (error) — Publication/open/write/flush failure.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the once, for the failing destination this is emitted once per.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once, for the failing destination.</remarks>
    public static DiagnosticOccurrence Path002(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? destination = null) =>
        Create("PATH002", DiagnosticSeverity.Error, phase, spec, message,
            cardinalityKey, destination: destination);

    /// <summary><c>LIMIT001</c> (error) — Non-wildcard resource limit exceeded.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <remarks>Cardinality: once per invocation.</remarks>
    public static DiagnosticOccurrence Limit001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null) =>
        Create("LIMIT001", DiagnosticSeverity.Error, phase, spec, message,
            Invocation, source: source, line: line, column: column, path: path);

    /// <summary><c>WARN001</c> (warning) — Missing input or scheme file.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the missing CLI path this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <remarks>Cardinality: once per missing CLI path.</remarks>
    public static DiagnosticOccurrence Warn001(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null) =>
        Create("WARN001", DiagnosticSeverity.Warning, phase, spec, message,
            cardinalityKey, source: source);

    /// <summary><c>WARN002</c> (warning) — Deprecated alias.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the alias category and scheme this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="declaration">Section 6.4.3 <c>declaration</c> member.</param>
    /// <remarks>Cardinality: once per alias category and scheme.</remarks>
    public static DiagnosticOccurrence Warn002(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? declaration = null) =>
        Create("WARN002", DiagnosticSeverity.Warning, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, declaration: declaration);

    /// <summary><c>WARN003</c> (warning) — Unsupported metadata/comment discarded or normalized.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the feature category and output file this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once per feature category and output file.</remarks>
    public static DiagnosticOccurrence Warn003(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        string? destination = null) =>
        Create("WARN003", DiagnosticSeverity.Warning, phase, spec, message,
            cardinalityKey, source: source, destination: destination);

    /// <summary><c>WARN004</c> (warning) — Native implicit sequences concatenate without explicit merge.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the sequence path this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <remarks>Cardinality: once per sequence path.</remarks>
    public static DiagnosticOccurrence Warn004(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        string? path = null) =>
        Create("WARN004", DiagnosticSeverity.Warning, phase, spec, message,
            cardinalityKey, source: source, path: path);

    /// <summary><c>WARN005</c> (warning) — Output destination collision or cross-format override.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the folded contribution pair this is emitted once per.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once per folded contribution pair.</remarks>
    public static DiagnosticOccurrence Warn005(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? destination = null) =>
        Create("WARN005", DiagnosticSeverity.Warning, phase, spec, message,
            cardinalityKey, destination: destination);

    /// <summary><c>WARN006</c> (warning) — Processing instruction discarded.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the input document this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <remarks>Cardinality: once per input document.</remarks>
    public static DiagnosticOccurrence Warn006(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null) =>
        Create("WARN006", DiagnosticSeverity.Warning, phase, spec, message,
            cardinalityKey, source: source);

    /// <summary><c>WARN007</c> (warning) — XML formatting whitespace discarded.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the input document this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <remarks>Cardinality: once per input document.</remarks>
    public static DiagnosticOccurrence Warn007(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null) =>
        Create("WARN007", DiagnosticSeverity.Warning, phase, spec, message,
            cardinalityKey, source: source);

    /// <summary><c>WARN008</c> (warning) — Output plan contains no destinations.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <remarks>Cardinality: once per invocation.</remarks>
    public static DiagnosticOccurrence Warn008(
        DiagnosticPhase phase,
        string spec,
        string message) =>
        Create("WARN008", DiagnosticSeverity.Warning, phase, spec, message,
            Invocation);

    /// <summary><c>WARN009</c> (warning) — Scheme directive binds to no effective output/path or wildcard output creates no instance.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the declaration or expanded directive this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="line">Section 6.4.3 <c>line</c> member.</param>
    /// <param name="column">Section 6.4.3 <c>column</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <param name="declaration">Section 6.4.3 <c>declaration</c> member.</param>
    /// <remarks>Cardinality: once per declaration or expanded directive.</remarks>
    public static DiagnosticOccurrence Warn009(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        int? line = null,
        int? column = null,
        string? path = null,
        string? declaration = null) =>
        Create("WARN009", DiagnosticSeverity.Warning, phase, spec, message,
            cardinalityKey, source: source, line: line, column: column, path: path, declaration: declaration);

    /// <summary><c>WARN010</c> (warning) — Native JSON/YAML numeric mapping remains inferred as sequence in an output view.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the source contribution, canonical mapping path, and output instance this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <param name="destination">Section 6.4.3 <c>destination</c> member.</param>
    /// <remarks>Cardinality: once per source contribution, canonical mapping path, and output instance.</remarks>
    public static DiagnosticOccurrence Warn010(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        string? path = null,
        string? destination = null) =>
        Create("WARN010", DiagnosticSeverity.Warning, phase, spec, message,
            cardinalityKey, source: source, path: path, destination: destination);

    /// <summary><c>WARN011</c> (warning) — Later unmarked contribution aliases an existing XML component instead of overriding it.</summary>
    /// <param name="phase">Emission phase of this occurrence.</param>
    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>
    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>
    /// <param name="cardinalityKey">Identity of the canonical path this is emitted once per.</param>
    /// <param name="source">Section 6.4.3 <c>source</c> member.</param>
    /// <param name="path">Section 6.4.3 <c>path</c> member.</param>
    /// <remarks>Cardinality: once per canonical path.</remarks>
    public static DiagnosticOccurrence Warn011(
        DiagnosticPhase phase,
        string spec,
        string message,
        string cardinalityKey,
        string? source = null,
        string? path = null) =>
        Create("WARN011", DiagnosticSeverity.Warning, phase, spec, message,
            cardinalityKey, source: source, path: path);
}
