<#
.SYNOPSIS
    Generates the derived documentation: the diagnostic reference and the migration guide.

.DESCRIPTION
    None of the output files is authored. docs/diagnostics.md and
    ansible/docs/diagnostics.md are rendered from one model derived from
    spec/diagnostics.registry.json, which is itself derived from the specification.
    docs/migration-2.x-to-3.0.md is assembled from the legacy.md that every conformance case is
    required to carry.

    The migration guide is generated rather than written because reconstructing the list of
    intentional divergences at release time produces a worse document than recording each one at the
    moment it is introduced, by the person who knew why.
#>
[CmdletBinding()]
param(
    [string] $RepositoryRoot = (Split-Path -Parent $PSScriptRoot),
    [switch] $DiagnosticsOnly
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$root = [IO.Path]::GetFullPath($RepositoryRoot)
$utf8 = New-Object Text.UTF8Encoding $false

function Write-Text([string] $Path, [string[]] $Lines) {
    [IO.File]::WriteAllText($Path, (($Lines -join "`n").TrimEnd() + "`n"), $utf8)
}

# ---------------------------------------------------------------- diagnostics

$registry = Get-Content (Join-Path $root 'spec/diagnostics.registry.json') -Raw | ConvertFrom-Json
$bundle = Get-Content (Join-Path $root 'spec/contract-bundle.json') -Raw | ConvertFrom-Json
$navigation = Get-Content (Join-Path $root 'spec/specification-navigation.json') -Raw | ConvertFrom-Json

if ($navigation.generatedBy -ne 'tools/sync-specification-navigation.ps1' -or
    $null -eq $navigation.clauses) {
    throw 'spec/specification-navigation.json is not a generated specification-navigation manifest.'
}

$specificationAnchors = @{}
foreach ($clause in $navigation.clauses) {
    $section = [string]$clause.section
    $anchor = [string]$clause.anchor
    if ([string]::IsNullOrWhiteSpace($section) -or [string]::IsNullOrWhiteSpace($anchor)) {
        throw 'spec/specification-navigation.json contains an incomplete clause.'
    }
    if ($specificationAnchors.ContainsKey($section)) {
        throw "spec/specification-navigation.json contains duplicate clause '$section'."
    }
    $specificationAnchors[$section] = $anchor
}

function Get-SpecificationAnchor([string] $Section) {
    if (-not $specificationAnchors.ContainsKey($Section)) {
        throw "spec/specification-navigation.json does not contain clause '$Section'."
    }
    return [string]$specificationAnchors[$Section]
}

$section22Anchor = Get-SpecificationAnchor '22'
$exampleAnchor = Get-SpecificationAnchor '6.4.3'
$appendixBAnchor = Get-SpecificationAnchor 'B'

$diagnostics = [Collections.Generic.List[object]]::new()
$diagnosticAnchors = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach ($code in $registry.codes) {
    $codeName = [string]$code.code
    $anchor = "diagnostic-$($codeName.ToLowerInvariant())"
    if (-not $diagnosticAnchors.Add($anchor)) {
        throw "Diagnostic codes produce the duplicate detail anchor '$anchor'."
    }

    $diagnostics.Add([pscustomobject][ordered]@{
        Code = $codeName
        Anchor = $anchor
        Severity = [string]$code.severity
        Cardinality = [string]$code.cardinality
        Condition = [string]$code.condition
        Fields = @($code.fields | ForEach-Object { [string]$_ })
        Mappings = @($code.mappings | ForEach-Object { [string]$_ })
    })
}

function Get-DiagnosticsLines(
    [string] $SpecificationUrl,
    [string] $SchemaUrl,
    [string] $ContributingUrl
) {
    $result = @(
    '<!-- Generated by tools/sync-docs.ps1 from spec/diagnostics.registry.json. Do not edit. -->'
    ''
    '# Diagnostic codes'
    ''
    "**Contract bundle ``$($bundle.revision)``.** $($registry.codes.Count) codes."
    ''
    'Every diagnostic this tool emits carries one of these codes, the phase it was raised in, and'
    "the specification anchor for the clause it enforces under [Section 22]($SpecificationUrl#$section22Anchor)."
    'Codes are stable across releases; messages are prose and may be reworded, so automate against'
    'the code and never against the text.'
    ''
    'Run with `--diagnostics-format json` to receive the whole stream on standard error as one'
    "canonical JSON array conforming to [``spec/diagnostic-stream.schema.json``]($SchemaUrl)."
    ''
    'The `spec` value is selected for each diagnostic occurrence; a code does not have one canonical'
    "clause. For example, ``§6.4.3`` resolves to [``§6.4.3``]($SpecificationUrl#$exampleAnchor)."
    ''
    '## Authority'
    ''
    "This registry is canonical for: $($registry.authoritativeFor -join '; ')."
    ''
    "It is **not** canonical for: $($registry.notAuthoritativeFor -join '; '). Those are owned by the"
    'specification prose. A disagreement between the two invalidates the build; it is never resolved'
    'by preference.'
    ''
    '## Codes'
    ''
    '| Code | Severity | Cardinality | Condition | Fields |'
    '|---|---|---|---|---|'
    )

    foreach ($diagnostic in $diagnostics) {
        $fields = if ($diagnostic.Fields.Count -eq 0) { '—' } else { ($diagnostic.Fields | ForEach-Object { "``$_``" }) -join ', ' }
        $result += "| [``$($diagnostic.Code)``](#$($diagnostic.Anchor)) | $($diagnostic.Severity) | $($diagnostic.Cardinality) | $($diagnostic.Condition) | $fields |"
    }

    $result += @(
    ''
    '## Conditions in detail'
    ''
    "Each code below lists the situations the specification maps to it ([Appendix B]($SpecificationUrl#$appendixBAnchor))."
    ''
    )

    foreach ($diagnostic in $diagnostics) {
        $result += "<a id=""$($diagnostic.Anchor)""></a>"
        $result += "### ``$($diagnostic.Code)`` — $($diagnostic.Condition)"
        $result += ''
        $result += "*$($diagnostic.Severity), $($diagnostic.Cardinality).*"
        $result += ''
        foreach ($mapping in $diagnostic.Mappings) {
            $result += "- $mapping"
        }
        $result += ''
    }

    $result += @(
    '## Disagreeing with a diagnostic'
    ''
    'If a diagnostic fires when you believe it should not, or does not fire when you believe it'
    'should, that is a finding worth reporting. Read the clause named by the `spec` anchor first,'
    'then route the report by asking what would have to change so this never surprises anyone again:'
    'the code, the specification, or the documentation. See'
    "[CONTRIBUTING.md]($ContributingUrl#4-the-feedback-channel-binding)."
    )

    return $result
}

$ansibleRef = (& python (Join-Path $PSScriptRoot 'sync-ansible-doc-links.py') --print-ref).Trim()
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($ansibleRef)) {
    throw 'Could not derive the immutable Ansible collection ref.'
}
$ansibleBase = "https://github.com/stop-cran/namespace2xml/blob/$ansibleRef"

$rootLines = Get-DiagnosticsLines `
    'specification.md' `
    '../spec/diagnostic-stream.schema.json' `
    '../CONTRIBUTING.md'
$ansibleLines = Get-DiagnosticsLines `
    "$ansibleBase/docs/specification.md" `
    "$ansibleBase/spec/diagnostic-stream.schema.json" `
    "$ansibleBase/CONTRIBUTING.md"

Write-Text (Join-Path $root 'docs/diagnostics.md') $rootLines
Write-Text (Join-Path $root 'ansible/docs/diagnostics.md') $ansibleLines
Write-Host "Wrote docs/diagnostics.md and ansible/docs/diagnostics.md ($($diagnostics.Count) codes)."

if ($DiagnosticsOnly) {
    return
}

# ------------------------------------------------------------------ migration

$cases = Get-ChildItem (Join-Path $root 'conformance') -Directory | Sort-Object Name

$verdicts = [ordered]@{ differs = @(); fails = @(); nondeterministic = @(); agrees = @() }
$silent = @()

foreach ($case in $cases) {
    $legacy = Join-Path $case.FullName 'legacy.md'
    if (-not (Test-Path $legacy)) { $silent += $case.Name; continue }

    $text = [IO.File]::ReadAllText($legacy) -replace "`r`n", "`n"
    $lines = $text -split "`n"

    $start = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^- namespace2xml 2\.4\.0: \*\*(?<verdict>[a-z]+)\*\*') {
            $start = $i
            $verdict = $Matches['verdict']
            break
        }
    }

    if ($start -lt 0) {
        throw ("$($case.Name): legacy.md declares no Appendix C.6 verdict. A case that carries the " +
            'file but no verdict line would be published under "same observable result, no note", ' +
            'which asserts the baseline reproduces the expected result. The line is ' +
            '"- namespace2xml 2.4.0: **<verdict>**", and the bold run must close at the verdict word.')
    }

    if (-not $verdicts.Contains($verdict)) {
        throw ("$($case.Name): legacy.md declares the verdict '$verdict', which is outside the " +
            "Appendix C.6 vocabulary ($($verdicts.Keys -join ', ')). An unrecognized verdict would " +
            'drop the case out of this document entirely.')
    }

    $end = $lines.Count - 1
    for ($i = $start + 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^#') { $end = $i - 1; break }
    }

    $block = (($lines[$start..$end]) -join "`n").Trim()
    $verdicts[$verdict] += [pscustomobject]@{ Name = $case.Name; Body = $block }
}

$lines = @(
    '<!-- Generated by tools/sync-docs.ps1 from each conformance case legacy.md. Do not edit. -->'
    ''
    '# Migrating from 2.x to 3.0'
    ''
    "**Contract bundle ``$($bundle.revision)``.**"
    ''
    '3.0 is a complete rewrite against a specification written before the implementation. Behaviour'
    'that 2.4.0 left undefined is now defined, and behaviour 2.4.0 got wrong is now corrected. This'
    'page lists every difference that a conformance case pins, assembled from the `legacy.md` that'
    'each case is required to carry.'
    ''
    'It is generated, and it is therefore complete only to the extent the corpus is. Cases still to'
    'be written are tracked in [KNOWN-LIMITS.md](../KNOWN-LIMITS.md).'
    ''
    '## Changes you must act on'
    ''
    '- **Target framework.** The tool now requires the .NET 10 runtime.'
    '- **Releases come from tags only.** If you pinned to a build produced by a push to `master`,'
    '  there is no longer such a build. Pin to a released version.'
    '- **3.0 is stable.** Install `namespace2xml` without `--prerelease`; use an exact version pin'
    '  when a deployment must remain on one contract build.'
    ''
    "## Observable differences ($($verdicts.differs.Count))"
    ''
    'Each of these is an observable difference between 2.4.0 and 3.0 on the same command line, and'
    'each was measured by running the pinned 2.4.0 baseline against the case rather than recalled.'
    'Nearly all are corrections, and every case says which contract it is correcting. A difference'
    'is not automatically an improvement, though: where 3.0 declines a capability 2.4.0'
    'implemented, its case says so plainly rather than letting the heading imply otherwise.'
    ''
)

if ($verdicts.differs.Count -eq 0) {
    $lines += '_None pinned by a conformance case yet._'
    $lines += ''
}
foreach ($entry in $verdicts.differs) {
    $lines += "### ``$($entry.Name)``"
    $lines += ''
    $lines += $entry.Body
    $lines += ''
}

$lines += @(
    "## Inputs 2.4.0 could not process ($($verdicts.fails.Count))"
    ''
    'The baseline exited nonzero on every sample of these, so no run of it completed: it refused the'
    'input, terminated abnormally, or gave up part way through, and each entry below says which. 3.0'
    'either accepts the input or reports a diagnostic and exits deliberately.'
    ''
)

if ($verdicts.fails.Count -eq 0) {
    $lines += '_None pinned by a conformance case yet._'
    $lines += ''
}
foreach ($entry in $verdicts.fails) {
    $lines += "### ``$($entry.Name)``"
    $lines += ''
    $lines += $entry.Body
    $lines += ''
}

if ($verdicts.nondeterministic.Count -gt 0) {
    $lines += @(
        "## Nondeterministic in 2.4.0 ($($verdicts.nondeterministic.Count))"
        ''
        'Repeated baseline runs of these cases do not agree with each other.'
        ''
    )
    foreach ($entry in $verdicts.nondeterministic) {
        $lines += "### ``$($entry.Name)``"
        $lines += ''
        $lines += $entry.Body
        $lines += ''
    }
}

$lines += @(
    "## Same observable result as 2.4.0 ($($verdicts.agrees.Count))"
    ''
    'The baseline produces this case''s expected output tree and exit code. That is a statement about'
    'the result and not about the reason: two tools exit `1` on the same command line whether they'
    'reject the same thing or entirely different things. Each entry below says which it is, and only'
    'those that name a shared reason are behaviour 3.0 preserved.'
    ''
)

if ($verdicts.agrees.Count -eq 0) {
    $lines += '_None pinned by a conformance case yet._'
    $lines += ''
}
foreach ($entry in $verdicts.agrees) {
    $lines += "### ``$($entry.Name)``"
    $lines += ''
    $lines += $entry.Body
    $lines += ''
}

if ($silent.Count -gt 0) {
    $lines += "## Same observable result, no note ($($silent.Count))"
    $lines += ''
    $lines += 'These cases declare no verdict. Appendix C.6 reads that as a claim that the baseline'
    $lines += 'reproduces the expected result, and the harness checks it against a real run, so their'
    $lines += 'silence is verified rather than assumed. They carry no note because nothing about the'
    $lines += 'difference needed explaining.'
    $lines += ''
    foreach ($name in $silent) {
        $lines += "- ``$name``"
    }
    $lines += ''
}

$lines += @(
    '## Something changed that is not listed here'
    ''
    'Then either a fixture is missing or the change was not intentional. Both are worth reporting:'
    '[pick a form](https://github.com/stop-cran/namespace2xml/issues/new/choose). Include the'
    '`contract-bundle` revision from `--version`.'
)

Write-Text (Join-Path $root 'docs/migration-2.x-to-3.0.md') $lines
Write-Host ("Wrote docs/migration-2.x-to-3.0.md ({0} differ, {1} fail, {2} nondeterministic, {3} agree, {4} silent)." -f
    $verdicts.differs.Count, $verdicts.fails.Count, $verdicts.nondeterministic.Count, $verdicts.agrees.Count, $silent.Count)
