<#
.SYNOPSIS
    Generates the derived documentation: the diagnostic reference and the migration guide.

.DESCRIPTION
    Neither file is authored. docs/diagnostics.md is derived from spec/diagnostics.registry.json,
    which is itself derived from the specification. docs/migration-2.x-to-3.0.md is assembled from
    the legacy.md that every conformance case is required to carry.

    The migration guide is generated rather than written because reconstructing the list of
    intentional divergences at release time produces a worse document than recording each one at the
    moment it is introduced, by the person who knew why.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$root = Split-Path -Parent $PSScriptRoot
$utf8 = New-Object Text.UTF8Encoding $false

function Write-Text([string] $Path, [string[]] $Lines) {
    [IO.File]::WriteAllText($Path, (($Lines -join "`n").TrimEnd() + "`n"), $utf8)
}

# ---------------------------------------------------------------- diagnostics

$registry = Get-Content (Join-Path $root 'spec/diagnostics.registry.json') -Raw | ConvertFrom-Json
$bundle = Get-Content (Join-Path $root 'spec/contract-bundle.json') -Raw | ConvertFrom-Json

$lines = @(
    '<!-- Generated by tools/sync-docs.ps1 from spec/diagnostics.registry.json. Do not edit. -->'
    ''
    '# Diagnostic codes'
    ''
    "**Contract bundle ``$($bundle.revision)``.** $($registry.codes.Count) codes."
    ''
    'Every diagnostic this tool emits carries one of these codes, the phase it was raised in, and'
    'the specification anchor for the clause it enforces. Codes are stable across releases; messages'
    'are prose and may be reworded, so automate against the code and never against the text.'
    ''
    'Run with `--diagnostics-format json` to receive the whole stream on standard error as one'
    'canonical JSON array conforming to [`spec/diagnostic-stream.schema.json`](../spec/diagnostic-stream.schema.json).'
    ''
    '## Authority'
    ''
    "This registry is canonical for: $($registry.authoritativeFor -join '; ')."
    ''
    "It is **not** canonical for: $($registry.notAuthoritativeFor -join '; '). Those are owned by the"
    'specification prose. A disagreement between the two invalidates the build; it is never resolved'
    'by preference.'
    ''
    '## Codes'
    ''
    '| Code | Severity | Cardinality | Condition | Fields |'
    '|---|---|---|---|---|'
)

foreach ($code in $registry.codes) {
    $fields = if ($code.fields.Count -eq 0) { '—' } else { ($code.fields | ForEach-Object { "``$_``" }) -join ', ' }
    $lines += "| ``$($code.code)`` | $($code.severity) | $($code.cardinality) | $($code.condition) | $fields |"
}

$lines += @(
    ''
    '## Conditions in detail'
    ''
    'Each code below lists the situations the specification maps to it (Appendix B).'
    ''
)

foreach ($code in $registry.codes) {
    $lines += "### ``$($code.code)`` — $($code.condition)"
    $lines += ''
    $lines += "*$($code.severity), $($code.cardinality).*"
    $lines += ''
    foreach ($mapping in $code.mappings) {
        $lines += "- $mapping"
    }
    $lines += ''
}

$lines += @(
    '## Disagreeing with a diagnostic'
    ''
    'If a diagnostic fires when you believe it should not, or does not fire when you believe it'
    'should, that is a finding worth reporting. Read the clause named by the `spec` anchor first,'
    'then route the report by asking what would have to change so this never surprises anyone again:'
    'the code, the specification, or the documentation. See'
    '[CONTRIBUTING.md](../CONTRIBUTING.md#4-the-feedback-channel-binding).'
)

Write-Text (Join-Path $root 'docs/diagnostics.md') $lines
Write-Host "Wrote docs/diagnostics.md ($($registry.codes.Count) codes)."

# ------------------------------------------------------------------ migration

$cases = Get-ChildItem (Join-Path $root 'conformance') -Directory | Sort-Object Name

$verdicts = [ordered]@{ differs = @(); crashes = @(); nondeterministic = @(); agrees = @() }
$silent = @()

foreach ($case in $cases) {
    $legacy = Join-Path $case.FullName 'legacy.md'
    if (-not (Test-Path $legacy)) { $silent += $case.Name; continue }

    $text = [IO.File]::ReadAllText($legacy) -replace "`r`n", "`n"
    $lines = $text -split "`n"

    $start = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^- namespace2xml 2\.4\.0: \*\*(?<verdict>[a-z]+)\*\*') {
            $start = $i
            $verdict = $Matches['verdict']
            break
        }
    }

    if ($start -lt 0) { $silent += $case.Name; continue }

    $end = $lines.Count - 1
    for ($i = $start + 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^#') { $end = $i - 1; break }
    }

    $block = (($lines[$start..$end]) -join "`n").Trim()
    $verdicts[$verdict] += [pscustomobject]@{ Name = $case.Name; Body = $block }
}

$lines = @(
    '<!-- Generated by tools/sync-docs.ps1 from each conformance case legacy.md. Do not edit. -->'
    ''
    '# Migrating from 2.x to 3.0'
    ''
    "**Contract bundle ``$($bundle.revision)``.**"
    ''
    '3.0 is a complete rewrite against a specification written before the implementation. Behaviour'
    'that 2.4.0 left undefined is now defined, and behaviour 2.4.0 got wrong is now corrected. This'
    'page lists every difference that a conformance case pins, assembled from the `legacy.md` that'
    'each case is required to carry.'
    ''
    'It is generated, and it is therefore complete only to the extent the corpus is. Cases still to'
    'be written are tracked in [KNOWN-LIMITS.md](../KNOWN-LIMITS.md).'
    ''
    '## Changes you must act on'
    ''
    '- **Target framework.** The tool now requires the .NET 10 runtime.'
    '- **Releases come from tags only.** If you pinned to a build produced by a push to `master`,'
    '  there is no longer such a build. Pin to a released version.'
    '- **Preview versions carry a `-preview.N` suffix.** `dotnet tool install` needs `--prerelease`.'
    ''
    "## Deliberate differences ($($verdicts.differs.Count))"
    ''
    'Each of these is an observable difference between 2.4.0 and 3.0 on the same command line, and'
    'each was measured by running the pinned 2.4.0 baseline against the case rather than recalled.'
    ''
)

if ($verdicts.differs.Count -eq 0) {
    $lines += '_None pinned by a conformance case yet._'
    $lines += ''
}
foreach ($entry in $verdicts.differs) {
    $lines += "### ``$($entry.Name)``"
    $lines += ''
    $lines += $entry.Body
    $lines += ''
}

$lines += @(
    "## Inputs that crashed 2.4.0 ($($verdicts.crashes.Count))"
    ''
    'The baseline terminates with an unhandled exception on these. 3.0 either accepts the input or'
    'reports a diagnostic and exits deliberately.'
    ''
)

if ($verdicts.crashes.Count -eq 0) {
    $lines += '_None pinned by a conformance case yet._'
    $lines += ''
}
foreach ($entry in $verdicts.crashes) {
    $lines += "### ``$($entry.Name)``"
    $lines += ''
    $lines += $entry.Body
    $lines += ''
}

if ($verdicts.nondeterministic.Count -gt 0) {
    $lines += @(
        "## Nondeterministic in 2.4.0 ($($verdicts.nondeterministic.Count))"
        ''
        'Repeated baseline runs of these cases do not agree with each other.'
        ''
    )
    foreach ($entry in $verdicts.nondeterministic) {
        $lines += "### ``$($entry.Name)``"
        $lines += ''
        $lines += $entry.Body
        $lines += ''
    }
}

$lines += @(
    "## Same observable result as 2.4.0 ($($verdicts.agrees.Count))"
    ''
    'The baseline produces this case''s expected output tree and exit code. That is a statement about'
    'the result and not about the reason: two tools exit `1` on the same command line whether they'
    'reject the same thing or entirely different things. Each entry below says which it is, and only'
    'those that name a shared reason are behaviour 3.0 preserved.'
    ''
)

if ($verdicts.agrees.Count -eq 0) {
    $lines += '_None pinned by a conformance case yet._'
    $lines += ''
}
foreach ($entry in $verdicts.agrees) {
    $lines += "### ``$($entry.Name)``"
    $lines += ''
    $lines += $entry.Body
    $lines += ''
}

if ($silent.Count -gt 0) {
    $lines += "## Same observable result, no note ($($silent.Count))"
    $lines += ''
    $lines += 'These cases declare no verdict. Appendix C.6 reads that as a claim that the baseline'
    $lines += 'reproduces the expected result, and the harness checks it against a real run, so their'
    $lines += 'silence is verified rather than assumed. They carry no note because nothing about the'
    $lines += 'difference needed explaining.'
    $lines += ''
    foreach ($name in $silent) {
        $lines += "- ``$name``"
    }
    $lines += ''
}

$lines += @(
    '## Something changed that is not listed here'
    ''
    'Then either a fixture is missing or the change was not intentional. Both are worth reporting:'
    '[pick a form](https://github.com/stop-cran/namespace2xml/issues/new/choose). Include the'
    '`contract-bundle` revision from `--version`.'
)

Write-Text (Join-Path $root 'docs/migration-2.x-to-3.0.md') $lines
Write-Host ("Wrote docs/migration-2.x-to-3.0.md ({0} differ, {1} crash, {2} nondeterministic, {3} agree, {4} silent)." -f
    $verdicts.differs.Count, $verdicts.crashes.Count, $verdicts.nondeterministic.Count, $verdicts.agrees.Count, $silent.Count)
