<#
.SYNOPSIS
    Generates the C# diagnostic factory surface from the Section 22 registry.

.DESCRIPTION
    spec/diagnostics.registry.json declares itself authoritative for four things: the set of codes,
    each code's severity, its cardinality, and the members it may carry. Restating any of those in
    hand-written C# creates a second copy that can disagree with the first, and a diagnostic emitted
    with the wrong severity is not something a schema validator or a byte comparison can catch.

    So the C# is derived instead. One factory per code, whose parameter list is exactly that code's
    permitted field set and whose severity is baked in, turns three classes of drift into compile
    errors at the call site rather than review comments.

    The output is checked in and gated by the contract-gates CI job, matching the four generators
    that already work this way. A source generator would also work, but a checked-in artifact is
    reviewable in the diff, which for a contract surface is the point.
#>
[CmdletBinding()]
param(
    [string] $RepositoryRoot = (Split-Path -Parent $PSScriptRoot)
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$registryPath = Join-Path $RepositoryRoot 'spec/diagnostics.registry.json'
$outputPath = Join-Path $RepositoryRoot 'src/Namespace2Xml.Core/Diagnostics/DiagnosticCodes.g.cs'

if (-not (Test-Path -LiteralPath $registryPath)) {
    throw "The diagnostic registry is missing at $registryPath. Run tools/sync-diagnostics-registry.ps1 first."
}

$registry = Get-Content -LiteralPath $registryPath -Raw | ConvertFrom-Json
if ($registry.codes.Count -eq 0) { throw "The diagnostic registry declares no codes." }

# Every member the Section 6.4.3 schema permits beyond the five required of each element, in schema
# order. A field the registry names but this map does not is a registry edit that outran the schema,
# and is a hard error rather than a silently dropped parameter.
$memberOrder = @('source', 'line', 'column', 'path', 'declaration', 'rule', 'destination')
$memberType = @{
    source      = 'string?'
    line        = 'int?'
    column      = 'int?'
    path        = 'string?'
    declaration = 'string?'
    rule        = 'string?'
    destination = 'string?'
}

function ConvertTo-MethodName {
    param([Parameter(Mandatory)][string] $Code)

    # CLI001 -> Cli001, REFERENCE005 -> Reference005. The trailing digits are part of the name.
    if ($Code -notmatch '^([A-Z]+)([0-9]+)$') {
        throw "Diagnostic code '$Code' is not <LETTERS><DIGITS>; the generator cannot name a method for it."
    }

    return $Matches[1].Substring(0, 1) + $Matches[1].Substring(1).ToLowerInvariant() + $Matches[2]
}

function ConvertTo-XmlDocText {
    param([Parameter(Mandatory)][AllowEmptyString()][string] $Text)

    return $Text.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;')
}

function ConvertTo-CSharpString {
    param([Parameter(Mandatory)][AllowEmptyString()][string] $Text)

    return '"' + $Text.Replace('\', '\\').Replace('"', '\"') + '"'
}

$lines = [System.Collections.Generic.List[string]]::new()
$add = { param([string] $line) $lines.Add($line) }

& $add '// <auto-generated>'
& $add '//     Generated by tools/sync-diagnostic-codes.ps1 from spec/diagnostics.registry.json.'
& $add '//     Do not edit. Change the registry, or the specification behind it, and regenerate.'
& $add '// </auto-generated>'
& $add ''
# The auto-generated header opts the file out of the project nullable context, so CS8669 rejects
# every `string?` below unless the context is restored explicitly.
& $add '#nullable enable'
& $add ''
& $add 'using System.Collections.Immutable;'
& $add ''
& $add 'namespace Namespace2Xml.Diagnostics;'
& $add ''
& $add 'public static partial class DiagnosticCodes'
& $add '{'
& $add '    /// <summary>'
& $add '    /// Every code in the Section 22 registry, in registry order, with the four facts the'
& $add '    /// registry declares itself authoritative for.'
& $add '    /// </summary>'
& $add '    public static ImmutableArray<DiagnosticCodeInfo> All { get; } ='
& $add '    ['

foreach ($entry in $registry.codes) {
    $severity = if ($entry.severity -eq 'error') { 'Error' } elseif ($entry.severity -eq 'warning') { 'Warning' } else {
        throw "Diagnostic code '$($entry.code)' has severity '$($entry.severity)', which is neither error nor warning."
    }

    $fieldList = if (@($entry.fields).Count -eq 0) { '[]' } else {
        '[' + ((@($entry.fields) | ForEach-Object { ConvertTo-CSharpString $_ }) -join ', ') + ']'
    }

    & $add ('        new DiagnosticCodeInfo(' + (ConvertTo-CSharpString $entry.code) + ', DiagnosticSeverity.' + $severity + ',')
    & $add ('            ' + (ConvertTo-CSharpString $entry.cardinality) + ',')
    & $add ('            ' + (ConvertTo-CSharpString $entry.condition) + ',')
    & $add ('            ' + $fieldList + '),')
}

& $add '    ];'

foreach ($entry in $registry.codes) {
    $code = $entry.code
    $method = ConvertTo-MethodName $code
    $severity = if ($entry.severity -eq 'error') { 'Error' } else { 'Warning' }
    $fields = @($entry.fields)

    foreach ($field in $fields) {
        if (-not $memberType.ContainsKey($field)) {
            throw "Diagnostic code '$code' declares field '$field', which is not a member of the Section 6.4.3 schema."
        }
    }

    # Registry order is not necessarily schema order; emit in schema order so every signature reads
    # the same way and matches the order members appear in the stream.
    $ordered = @($memberOrder | Where-Object { $fields -contains $_ })
    $scopedToInvocation = $entry.cardinality -eq 'once per invocation'

    & $add ''
    & $add ('    /// <summary><c>' + $code + '</c> (' + $entry.severity + ') — ' + (ConvertTo-XmlDocText $entry.condition) + '.</summary>')
    & $add '    /// <param name="phase">Emission phase of this occurrence.</param>'
    & $add '    /// <param name="spec">Anchor of the clause being enforced, for example <c>§13.1</c>.</param>'
    & $add '    /// <param name="message">Localizable prose. Never compared by the conformance harness.</param>'

    if (-not $scopedToInvocation) {
        & $add ('    /// <param name="cardinalityKey">Identity of the ' + (ConvertTo-XmlDocText ($entry.cardinality -replace '^once,? per ', '')) + ' this is emitted once per.</param>')
    }

    foreach ($field in $ordered) {
        & $add ('    /// <param name="' + $field + '">Section 6.4.3 <c>' + $field + '</c> member.</param>')
    }

    & $add ('    /// <remarks>Cardinality: ' + (ConvertTo-XmlDocText $entry.cardinality) + '.</remarks>')
    & $add ('    public static DiagnosticOccurrence ' + $method + '(')

    $parameters = [System.Collections.Generic.List[string]]::new()
    $parameters.Add('DiagnosticPhase phase')
    $parameters.Add('string spec')
    $parameters.Add('string message')
    if (-not $scopedToInvocation) {
        $parameters.Add('string cardinalityKey')
    }
    foreach ($field in $ordered) {
        $parameters.Add($memberType[$field] + ' ' + $field + ' = null')
    }

    for ($i = 0; $i -lt $parameters.Count; $i++) {
        $suffix = if ($i -eq $parameters.Count - 1) { ') =>' } else { ',' }
        & $add ('        ' + $parameters[$i] + $suffix)
    }

    & $add ('        Create(' + (ConvertTo-CSharpString $code) + ', DiagnosticSeverity.' + $severity + ', phase, spec, message,')

    $key = if ($scopedToInvocation) { 'Invocation' } else { 'cardinalityKey' }
    $arguments = @($key) + @($ordered | ForEach-Object { $_ + ': ' + $_ })
    & $add ('            ' + ($arguments -join ', ') + ');')
}

& $add '}'

$text = ($lines -join "`n") + "`n"
[System.IO.File]::WriteAllText($outputPath, $text, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Wrote $($registry.codes.Count) diagnostic factories to $outputPath."
