<#
.SYNOPSIS
    Generates the derived documentation: the diagnostic reference and the migration guide.

.DESCRIPTION
    Neither file is authored. docs/diagnostics.md is derived from spec/diagnostics.registry.json,
    which is itself derived from the specification. docs/migration-2.x-to-3.0.md is assembled from
    the legacy.md that every conformance case is required to carry.

    The migration guide is generated rather than written because reconstructing the list of
    intentional divergences at release time produces a worse document than recording each one at the
    moment it is introduced, by the person who knew why.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$root = Split-Path -Parent $PSScriptRoot
$utf8 = New-Object Text.UTF8Encoding $false

function Write-Text([string] $Path, [string[]] $Lines) {
    [IO.File]::WriteAllText($Path, (($Lines -join "`n").TrimEnd() + "`n"), $utf8)
}

# ---------------------------------------------------------------- diagnostics

$registry = Get-Content (Join-Path $root 'spec/diagnostics.registry.json') -Raw | ConvertFrom-Json
$bundle = Get-Content (Join-Path $root 'spec/contract-bundle.json') -Raw | ConvertFrom-Json

$lines = @(
    '<!-- Generated by tools/sync-docs.ps1 from spec/diagnostics.registry.json. Do not edit. -->'
    ''
    '# Diagnostic codes'
    ''
    "**Contract bundle ``$($bundle.revision)``.** $($registry.codes.Count) codes."
    ''
    'Every diagnostic this tool emits carries one of these codes, the phase it was raised in, and'
    'the specification anchor for the clause it enforces. Codes are stable across releases; messages'
    'are prose and may be reworded, so automate against the code and never against the text.'
    ''
    'Run with `--diagnostics-format json` to receive the whole stream on standard error as one'
    'canonical JSON array conforming to [`spec/diagnostic-stream.schema.json`](../spec/diagnostic-stream.schema.json).'
    ''
    '## Authority'
    ''
    "This registry is canonical for: $($registry.authoritativeFor -join '; ')."
    ''
    "It is **not** canonical for: $($registry.notAuthoritativeFor -join '; '). Those are owned by the"
    'specification prose. A disagreement between the two invalidates the build; it is never resolved'
    'by preference.'
    ''
    '## Codes'
    ''
    '| Code | Severity | Cardinality | Condition | Fields |'
    '|---|---|---|---|---|'
)

foreach ($code in $registry.codes) {
    $fields = if ($code.fields.Count -eq 0) { '—' } else { ($code.fields | ForEach-Object { "``$_``" }) -join ', ' }
    $lines += "| ``$($code.code)`` | $($code.severity) | $($code.cardinality) | $($code.condition) | $fields |"
}

$lines += @(
    ''
    '## Conditions in detail'
    ''
    'Each code below lists the situations the specification maps to it (Appendix B).'
    ''
)

foreach ($code in $registry.codes) {
    $lines += "### ``$($code.code)`` — $($code.condition)"
    $lines += ''
    $lines += "*$($code.severity), $($code.cardinality).*"
    $lines += ''
    foreach ($mapping in $code.mappings) {
        $lines += "- $mapping"
    }
    $lines += ''
}

$lines += @(
    '## Disagreeing with a diagnostic'
    ''
    'If a diagnostic fires when you believe it should not, or does not fire when you believe it'
    'should, that is a finding worth reporting. Read the clause named by the `spec` anchor first,'
    'then route the report by asking what would have to change so this never surprises anyone again:'
    'the code, the specification, or the documentation. See'
    '[CONTRIBUTING.md](../CONTRIBUTING.md#4-the-feedback-channel-binding).'
)

Write-Text (Join-Path $root 'docs/diagnostics.md') $lines
Write-Host "Wrote docs/diagnostics.md ($($registry.codes.Count) codes)."

# ------------------------------------------------------------------ migration

$cases = Get-ChildItem (Join-Path $root 'conformance') -Directory | Sort-Object Name

$agrees = @()
$differs = @()
$unclassified = @()

foreach ($case in $cases) {
    $legacy = Join-Path $case.FullName 'legacy.md'
    if (-not (Test-Path $legacy)) { continue }

    $text = [IO.File]::ReadAllText($legacy) -replace "`r`n", "`n"
    $body = ($text -split "`n" | Where-Object { $_ -notmatch '^#' }) -join "`n"

    $entry = [pscustomobject]@{ Name = $case.Name; Body = $body.Trim() }

    if ($text -match '\*\*agrees\*\*') { $agrees += $entry }
    elseif ($text -match '\*\*differs\*\*') { $differs += $entry }
    else { $unclassified += $entry }
}

$lines = @(
    '<!-- Generated by tools/sync-docs.ps1 from each conformance case legacy.md. Do not edit. -->'
    ''
    '# Migrating from 2.x to 3.0'
    ''
    "**Contract bundle ``$($bundle.revision)``.**"
    ''
    '3.0 is a complete rewrite against a specification written before the implementation. Behaviour'
    'that 2.4.0 left undefined is now defined, and behaviour 2.4.0 got wrong is now corrected. This'
    'page lists every difference that a conformance case pins, assembled from the `legacy.md` that'
    'each case is required to carry.'
    ''
    'It is generated, and it is therefore complete only to the extent the corpus is. Cases still to'
    'be written are tracked in [KNOWN-LIMITS.md](../KNOWN-LIMITS.md).'
    ''
    '## Changes you must act on'
    ''
    '- **Target framework.** The tool now requires the .NET 10 runtime.'
    '- **Releases come from tags only.** If you pinned to a build produced by a push to `master`,'
    '  there is no longer such a build. Pin to a released version.'
    '- **Preview versions carry a `-preview.N` suffix.** `dotnet tool install` needs `--prerelease`.'
    ''
    "## Deliberate differences ($($differs.Count))"
    ''
)

if ($differs.Count -eq 0) {
    $lines += '_None pinned by a conformance case yet._'
    $lines += ''
}
foreach ($entry in $differs) {
    $lines += "### ``$($entry.Name)``"
    $lines += ''
    $lines += $entry.Body
    $lines += ''
}

$lines += @(
    "## Behaviour preserved from 2.4.0 ($($agrees.Count))"
    ''
    'These cases pin behaviour that 2.4.0 already had. They exist so a future change cannot lose it'
    'silently.'
    ''
)

if ($agrees.Count -eq 0) {
    $lines += '_None pinned by a conformance case yet._'
    $lines += ''
}
foreach ($entry in $agrees) {
    $lines += "### ``$($entry.Name)``"
    $lines += ''
    $lines += $entry.Body
    $lines += ''
}

if ($unclassified.Count -gt 0) {
    $lines += '## Unclassified'
    $lines += ''
    $lines += 'These cases carry a `legacy.md` that states neither agreement nor difference. That is a'
    $lines += 'defect in the fixture; see CONTRIBUTING.md.'
    $lines += ''
    foreach ($entry in $unclassified) {
        $lines += "- ``$($entry.Name)``"
    }
    $lines += ''
}

$lines += @(
    '## Something changed that is not listed here'
    ''
    'Then either a fixture is missing or the change was not intentional. Both are worth reporting:'
    '[pick a form](https://github.com/stop-cran/namespace2xml/issues/new/choose). Include the'
    '`contract-bundle` revision from `--version`.'
)

Write-Text (Join-Path $root 'docs/migration-2.x-to-3.0.md') $lines
Write-Host "Wrote docs/migration-2.x-to-3.0.md ($($differs.Count) differences, $($agrees.Count) preserved, $($unclassified.Count) unclassified)."
